### ISSUE TITLE
[Initializer] Annotations with structs only classified as old syntax

### ISSUE THREAD

**Issue by DomenicoCacace** [TAFFO-org/TAFFO#3]
Annotations that contain only structs (e.g. `struct[void]`), which are valid in the [new syntax](https://github.com/TAFFO-org/TAFFO/blob/master/doc/AnnotationSyntax.md#struct), are classified as written with the old syntax.

https://github.com/TAFFO-org/TAFFO/blob/a1051f84da2482da8a84295a8f5f85220d0f740b/unittests/Initializer/TaffoInitializer/AnnotationParserTest.cpp#L532-L543
<pre><code>
[ RUN      ] AnnotationParserTest.StructVoid
TAFFO/unittests/Initializer/TaffoInitializer/AnnotationParserTest.cpp:537: Failure
      Expected: NO_ERR
      Which is: ""
To be equal to: error
      Which is: <b>"Somebody used the old syntax and they should stop."</b>
TAFFO/unittests/Initializer/TaffoInitializer/AnnotationParserTest.cpp:538: Failure
Value of: res
  Actual: false
Expected: true
[  FAILED  ] AnnotationParserTest.StructVoid (0 ms)

</code>

**Comment by danielecattaneo** [comment]
Fixed in 3fcdbd3.
