### ISSUE TITLE
[Initializer] Zero is not considered as integer

### ISSUE THREAD

**Issue by DomenicoCacace** [TAFFO-org/TAFFO#4]
The number 0 is not parsed as an integer.

https://github.com/TAFFO-org/TAFFO/blob/a1051f84da2482da8a84295a8f5f85220d0f740b/unittests/Initializer/TaffoInitializer/AnnotationParserTest.cpp#L649-L658
<pre><code>
[ RUN      ] AnnotationParserTest.IntegerZero
TAFFO/unittests/Initializer/TaffoInitializer/AnnotationParserTest.cpp:654: Failure
      Expected: NO_ERR
      Which is: ""
To be equal to: error
      Which is: <b>"Expected integer at character index 13"</b>
TAFFO/unittests/Initializer/TaffoInitializer/AnnotationParserTest.cpp:655: Failure
Value of: res
  Actual: false
Expected: true
[  FAILED  ] AnnotationParserTest.IntegerZero (1 ms)
</code>

**Comment by danielecattaneo** [comment]
Fixed in 3fcdbd3.
