### ISSUE TITLE
[Initializer] Integer base conversion is not correct

### ISSUE THREAD

**Issue by DomenicoCacace** [TAFFO-org/TAFFO#5]
When parsing integers in base 16, the result in base 10 does not correspond to the original value.

https://github.com/TAFFO-org/TAFFO/blob/a1051f84da2482da8a84295a8f5f85220d0f740b/unittests/Initializer/TaffoInitializer/AnnotationParserTest.cpp#L729-L739
<pre><code>
[ RUN      ] AnnotationParserTest.IntegerNoSignBase16
TAFFO/unittests/Initializer/TaffoInitializer/AnnotationParserTest.cpp:738: Failure
      Expected: parser.backtrackingDepth
      Which is: <b>2309737967</b>
To be equal to: <b>81985529216486895</b>
[  FAILED  ] AnnotationParserTest.IntegerNoSignBase16 (0 ms)
</code></pre>

https://github.com/TAFFO-org/TAFFO/blob/a1051f84da2482da8a84295a8f5f85220d0f740b/unittests/Initializer/TaffoInitializer/AnnotationParserTest.cpp#L741-L751
<pre><code>
[ RUN      ] AnnotationParserTest.IntegerPositiveSignBase16
TAFFO/unittests/Initializer/TaffoInitializer/AnnotationParserTest.cpp:750: Failure
      Expected: parser.backtrackingDepth
      Which is: <b>2309737967</b>
To be equal to: <b>81985529216486895</b>
[  FAILED  ] AnnotationParserTest.IntegerPositiveSignBase16 (0 ms)
</code></pre>

https://github.com/TAFFO-org/TAFFO/blob/a1051f84da2482da8a84295a8f5f85220d0f740b/unittests/Initializer/TaffoInitializer/AnnotationParserTest.cpp#L753-L763
<pre><code>
[ RUN      ] AnnotationParserTest.IntegerNegativeSignBase16
TAFFO/unittests/Initializer/TaffoInitializer/AnnotationParserTest.cpp:762: Failure
      Expected: parser.backtrackingDepth
      Which is: <b>1985229329</b>
To be equal to: <b>-81985529216486895</b>
[  FAILED  ] AnnotationParserTest.IntegerNegativeSignBase16 (0 ms)
</code></pre>

**Comment by danielecattaneo** [comment]
This was only due to truncation to 32 bits due to the use of int/unsigned variables, so this is actually intended behavior.
