### ISSUE TITLE
[Initializer] Failing check on octal integer digits

### ISSUE THREAD

**Issue by DomenicoCacace** [TAFFO-org/TAFFO#6]
Octal integers (starting with `0`) are parsed succesfully even if they contain 8 and/or 9 as digits.

https://github.com/TAFFO-org/TAFFO/blob/a1051f84da2482da8a84295a8f5f85220d0f740b/unittests/Initializer/TaffoInitializer/AnnotationParserTest.cpp#L765-L771
<pre><code>
[ RUN      ] AnnotationParserTest.IntegerInvalidOctal
TAFFO/unittests/Initializer/TaffoInitializer/AnnotationParserTest.cpp:770: Failure
Value of: res
  Actual: true
Expected: false
[  FAILED  ] AnnotationParserTest.IntegerInvalidOctal (0 ms)
</code></pre>

**Comment by danielecattaneo** [comment]
Fixed in 3fcdbd3.
